/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ProjetoImobiliaria;

import ImobiliariaEnum.LocacaoEstado;
import ClassesImobiliaria.*;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dionm
 */
public class LocacaoIU extends javax.swing.JFrame {

    private String modo = "navegar";

    public LocacaoIU() {
        initComponents();
        setLocationRelativeTo(null);

        carregarTabelaLocacao();
        controleInterface();

        setDefaultCloseOperation(0);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                ImobiliariaIU.janelaLocacao.show(false);
            }
        });
    }

    private void controleInterface() {
        switch (modo) {
            case "navegar":
                btn_locac_LimparLocacao.setEnabled(false);
                btn_locac_alugar.setEnabled(false);
                btn_locac_alugar_ok.setEnabled(false);
                btn_locac_anunciar.setEnabled(false);
                btn_locac_anunciar_ok.setEnabled(false);
                btn_locac_cancelar.setEnabled(false);
                btn_locac_despejar.setEnabled(false);

                cons_locac_inquilino.setEnabled(false);
                cons_locac_preco.setEnabled(false);
                cons_locac_CPF.setEnabled(false);

                cons_locac_CPF.setText("");
                cons_locac_inquilino.setText("");
                cons_locac_preco.setText("");

                carregarTabelaLocacao();
                break;
        }
    }

    private void carregarTabelaLocacao() {

        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Tipo Imovel", "Nº Matricula", "Preço", "Estado", "Inquilino"}, 0);

        List<Locacao> locacao_aux = ImobiliariaIU.imobiliaria.ListaLocações();

        locacao_aux.forEach((locacao) -> {

            if (locacao.getEstado() != LocacaoEstado.Alugado) {
                modelo.addRow(new Object[]{locacao.getTipoImovel(), locacao.getNumeroImovel(), locacao.getValor(), locacao.getEstado(), "Livre"});
            } else {
                modelo.addRow(new Object[]{locacao.getTipoImovel(), locacao.getNumeroImovel(), locacao.getValor(), locacao.getEstado(), locacao.getInquilino()});
            }
        });

        tbl_locac_registroGeral.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbl_geral = new javax.swing.JTabbedPane();
        tbl_panel_locacao = new javax.swing.JPanel();
        btn_locac_anunciar = new javax.swing.JButton();
        btn_locac_alugar = new javax.swing.JButton();
        cons_locac_preco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cons_locac_inquilino = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_locac_registroGeral = new javax.swing.JTable();
        btn_locac_cancelar = new javax.swing.JButton();
        btn_locac_anunciar_ok = new javax.swing.JButton();
        btn_locac_alugar_ok = new javax.swing.JButton();
        btn_locac_despejar = new javax.swing.JButton();
        btn_locac_LimparLocacao = new javax.swing.JButton();
        btn_loc_atualizarTabela = new javax.swing.JButton();
        cons_locac_CPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cons_locac_valorParcela = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        tbl_geral.setToolTipText("");

        btn_locac_anunciar.setText("Anunciar");
        btn_locac_anunciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_anunciarActionPerformed(evt);
            }
        });

        btn_locac_alugar.setText("Alugar");
        btn_locac_alugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_alugarActionPerformed(evt);
            }
        });

        jLabel4.setText("Preço:");

        jLabel5.setText("Inquilino:");

        tbl_locac_registroGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imovel", "Nº Matricula", "Preço", "Estado", "Inquilino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_locac_registroGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_locac_registroGeralMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_locac_registroGeral);
        if (tbl_locac_registroGeral.getColumnModel().getColumnCount() > 0) {
            tbl_locac_registroGeral.getColumnModel().getColumn(0).setResizable(false);
            tbl_locac_registroGeral.getColumnModel().getColumn(1).setResizable(false);
            tbl_locac_registroGeral.getColumnModel().getColumn(2).setResizable(false);
            tbl_locac_registroGeral.getColumnModel().getColumn(3).setResizable(false);
            tbl_locac_registroGeral.getColumnModel().getColumn(4).setResizable(false);
        }

        btn_locac_cancelar.setForeground(new java.awt.Color(255, 0, 0));
        btn_locac_cancelar.setText("Cancelar");
        btn_locac_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_cancelarActionPerformed(evt);
            }
        });

        btn_locac_anunciar_ok.setText("OK");
        btn_locac_anunciar_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_anunciar_okActionPerformed(evt);
            }
        });

        btn_locac_alugar_ok.setText("OK");
        btn_locac_alugar_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_alugar_okActionPerformed(evt);
            }
        });

        btn_locac_despejar.setText("Despejar");
        btn_locac_despejar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_despejarActionPerformed(evt);
            }
        });

        btn_locac_LimparLocacao.setForeground(new java.awt.Color(255, 0, 0));
        btn_locac_LimparLocacao.setText("Limpa Locação");
        btn_locac_LimparLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locac_LimparLocacaoActionPerformed(evt);
            }
        });

        btn_loc_atualizarTabela.setText("Atualizar Tabela");
        btn_loc_atualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loc_atualizarTabelaActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF:");

        jLabel2.setText("Valor Parcela:");

        javax.swing.GroupLayout tbl_panel_locacaoLayout = new javax.swing.GroupLayout(tbl_panel_locacao);
        tbl_panel_locacao.setLayout(tbl_panel_locacaoLayout);
        tbl_panel_locacaoLayout.setHorizontalGroup(
            tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_locacaoLayout.createSequentialGroup()
                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                .addComponent(btn_locac_cancelar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_locac_anunciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_locac_alugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cons_locac_valorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel4)
                                                .addGap(23, 23, 23))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel1))
                                                .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                                    .addGap(0, 0, Short.MAX_VALUE)
                                                    .addComponent(jLabel5))))
                                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(cons_locac_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cons_locac_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cons_locac_inquilino, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(18, 18, 18)
                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                .addComponent(btn_locac_alugar_ok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_locac_despejar))
                            .addComponent(btn_locac_anunciar_ok))
                        .addGap(252, 252, 252))
                    .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                                .addComponent(btn_locac_LimparLocacao)
                                .addGap(194, 194, 194)
                                .addComponent(btn_loc_atualizarTabela)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tbl_panel_locacaoLayout.setVerticalGroup(
            tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_locac_anunciar)
                    .addComponent(cons_locac_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btn_locac_anunciar_ok))
                .addGap(33, 33, 33)
                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_locac_alugar)
                    .addComponent(jLabel5)
                    .addComponent(cons_locac_inquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_locac_alugar_ok)
                    .addComponent(btn_locac_despejar))
                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btn_locac_cancelar)
                        .addGap(23, 23, 23))
                    .addGroup(tbl_panel_locacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cons_locac_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cons_locac_valorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tbl_panel_locacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_locac_LimparLocacao)
                    .addComponent(btn_loc_atualizarTabela))
                .addGap(6, 6, 6))
        );

        tbl_geral.addTab("Locação", tbl_panel_locacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tbl_geral, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_geral, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_locac_LimparLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_LimparLocacaoActionPerformed
        int indice = tbl_locac_registroGeral.getSelectedRow();
        List<Locacao> locacao_aux = ImobiliariaIU.imobiliaria.ListaLocações();

        if (indice >= 0 && indice < locacao_aux.size()) {
            if (locacao_aux.get(indice).getEstado() != LocacaoEstado.Alugado) {
                locacao_aux.remove(locacao_aux.get(indice));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Meio complicado apagar esse registro com alguém morando nele.", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }
        carregarTabelaLocacao();
    }//GEN-LAST:event_btn_locac_LimparLocacaoActionPerformed

    private void btn_locac_despejarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_despejarActionPerformed
        int indice = tbl_locac_registroGeral.getSelectedRow();
        List<Locacao> locacao_aux = ImobiliariaIU.imobiliaria.ListaLocações();

        if (indice >= 0 && indice < locacao_aux.size()) {
            if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Alugado) {
                locacao_aux.get(indice).alugar(locacao_aux.get(indice).getValor());
            }
        }

        locacao_aux.get(indice).setInquilino("Vazio", "Vazio");
        carregarTabelaLocacao();
    }//GEN-LAST:event_btn_locac_despejarActionPerformed

    private void btn_locac_alugar_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_alugar_okActionPerformed
        int indice = tbl_locac_registroGeral.getSelectedRow();
        String inquilino_aux = cons_locac_inquilino.getText();
        String CPF_aux = cons_locac_CPF.getText();

        List<Locacao> locacao_aux = ImobiliariaIU.imobiliaria.ListaLocações();

        if (indice >= 0 && indice <= locacao_aux.size()) {
            if (inquilino_aux != "" && CPF_aux != "") {
                if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Alugar) {
                    locacao_aux.get(indice).finalizar(inquilino_aux, CPF_aux);
                }
            }
        }

        controleInterface();
    }//GEN-LAST:event_btn_locac_alugar_okActionPerformed

    private void btn_locac_anunciar_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_anunciar_okActionPerformed

        int indice = tbl_locac_registroGeral.getSelectedRow();
        String valor_aux = cons_locac_preco.getText();
        List<Locacao> locacao_aux = ImobiliariaIU.imobiliaria.ListaLocações();

        if (indice >= 0 && indice <= locacao_aux.size()) {
            if (valor_aux != "") {
                if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Disponivel) {
                    locacao_aux.get(indice).alugar(valor_aux);
                }
            }
        }

        carregarTabelaLocacao();

        modo = "navegar";
        controleInterface();
    }//GEN-LAST:event_btn_locac_anunciar_okActionPerformed

    private void btn_locac_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_cancelarActionPerformed

        modo = "navegar";

        controleInterface();

    }//GEN-LAST:event_btn_locac_cancelarActionPerformed

    private void tbl_locac_registroGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_locac_registroGeralMouseClicked
        List<Locacao> locacao_aux = ImobiliariaIU.imobiliaria.ListaLocações();

        int indice = tbl_locac_registroGeral.getSelectedRow();

        if (indice >= 0 && indice <= locacao_aux.size()) {
            if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Disponivel) {
                btn_locac_anunciar.setEnabled(true);
            } else if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Alugar) {
                btn_locac_alugar.setEnabled(true);
            }
            if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Alugado) {
                btn_locac_despejar.setEnabled(true);
            }
        }

        if (locacao_aux.get(indice).getEstado() == LocacaoEstado.Alugado) {
            cons_locac_inquilino.setText(locacao_aux.get(indice).getInquilino());
        }

        btn_locac_cancelar.setEnabled(true);
        btn_locac_LimparLocacao.setEnabled(true);
    }//GEN-LAST:event_tbl_locac_registroGeralMouseClicked

    private void btn_locac_alugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_alugarActionPerformed
        btn_locac_alugar_ok.setEnabled(true);
        cons_locac_inquilino.setEnabled(true);
        cons_locac_CPF.setEnabled(true);
        btn_locac_alugar.setEnabled(false);
    }//GEN-LAST:event_btn_locac_alugarActionPerformed

    private void btn_locac_anunciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locac_anunciarActionPerformed
        btn_locac_anunciar_ok.setEnabled(true);
        cons_locac_preco.setEnabled(true);
        btn_locac_anunciar.setEnabled(false);
    }//GEN-LAST:event_btn_locac_anunciarActionPerformed

    private void btn_loc_atualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loc_atualizarTabelaActionPerformed
        carregarTabelaLocacao();
    }//GEN-LAST:event_btn_loc_atualizarTabelaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("dfsdfsfsdfsdfsd");
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocacaoIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocacaoIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocacaoIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocacaoIU.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LocacaoIU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_loc_atualizarTabela;
    private javax.swing.JButton btn_locac_LimparLocacao;
    private javax.swing.JButton btn_locac_alugar;
    private javax.swing.JButton btn_locac_alugar_ok;
    private javax.swing.JButton btn_locac_anunciar;
    private javax.swing.JButton btn_locac_anunciar_ok;
    private javax.swing.JButton btn_locac_cancelar;
    private javax.swing.JButton btn_locac_despejar;
    private javax.swing.JTextField cons_locac_CPF;
    private javax.swing.JTextField cons_locac_inquilino;
    private javax.swing.JTextField cons_locac_preco;
    private javax.swing.JTextField cons_locac_valorParcela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tbl_geral;
    private javax.swing.JTable tbl_locac_registroGeral;
    private javax.swing.JPanel tbl_panel_locacao;
    // End of variables declaration//GEN-END:variables
}
